# Generated by Django 5.0.3 on 2024-03-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lan_name', models.CharField(max_length=50, verbose_name='Language name')),
                ('lan_info', models.CharField(max_length=255, verbose_name='Language info')),
            ],
            options={
                'verbose_name': 'Language',
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Freamworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fw_name', models.CharField(max_length=50, verbose_name='Freamwork name')),
                ('fw_info', models.CharField(max_length=255, verbose_name='Freamwork info')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_languages.languages')),
            ],
            options={
                'verbose_name': 'FREAMWORKS',
                'db_table': 'freamworks',
            },
        ),
    ]
